{
 "title": "Tesla Wall Charger",
 "tags": [ "tesla" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "kw_cost", "label": "kW Cost", "query": "0.20" }
  ]
 },
 "panels": [
  {
   "title": "WIFI",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tesla_wifi_status_wifi_connected",
     "legendFormat": "WIFI"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tesla_vital_temp_mcu_temp_c", "legendFormat": "mcu" },
    { "expr": "tesla_vital_temp_handle_temp_c", "legendFormat": "handle" },
    { "expr": "tesla_vital_temp_pcba_temp_c", "legendFormat": "pcba" }
   ]
  },
  {
   "title": "Amps",
   "type": "timeseries",
   "description": "Current",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "tesla_vital_current_currentA_a", "legendFormat": "L1" },
    { "expr": "tesla_vital_current_currentB_a", "legendFormat": "L2" },
    { "expr": "tesla_vital_current_currentC_a", "legendFormat": "L3" },
    { "expr": "tesla_vital_current_currentN_a", "legendFormat": "N" },
    {
     "expr": "tesla_vital_current_vehicle_current_a",
     "legendFormat": "Car"
    }
   ]
  },
  {
   "title": "Voltages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "tesla_vital_voltage_voltageA_v", "legendFormat": "L1" },
    { "expr": "tesla_vital_voltage_voltageB_v", "legendFormat": "L2" },
    { "expr": "tesla_vital_voltage_voltageC_v", "legendFormat": "L3" },
    { "expr": "tesla_vital_grid_grid_v", "legendFormat": "Grid" }
   ]
  },
  {
   "title": "Vehicle",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tesla_vital_vehicle_vehicle_connected",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EVSE State",
   "type": "stat",
   "description": "State",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tesla_vital_state_evse_state", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "tesla_vital_temp_mcu_temp_c", "legendFormat": "mcu" },
    { "expr": "tesla_vital_temp_handle_temp_c", "legendFormat": "handle" },
    { "expr": "tesla_vital_temp_pcba_temp_c", "legendFormat": "pcba" }
   ]
  },
  {
   "title": "Watt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "tesla_vital_voltage_voltageA_v * on(device) group_left() tesla_vital_current_currentA_a",
     "legendFormat": "L1"
    },
    {
     "expr": "tesla_vital_voltage_voltageB_v * on(device) group_left() tesla_vital_current_currentB_a",
     "legendFormat": "L2"
    },
    {
     "expr": "tesla_vital_voltage_voltageC_v * on(device) group_left() tesla_vital_current_currentC_a",
     "legendFormat": "L3"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tesla_lifetime_uptime_s", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Charging Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tesla_lifetime_charging_time_s", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Grid Hz",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    { "expr": "tesla_vital_grid_grid_hz", "legendFormat": "Hz" }
   ]
  },
  {
   "title": "WiFi",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "tesla_wifi_status_wifi_signal_strength",
     "legendFormat": "Signal Strength"
    },
    { "expr": "tesla_wifi_status_wifi_rssi", "legendFormat": "RSSI" },
    { "expr": "tesla_wifi_status_wifi_snr", "legendFormat": "SNR" }
   ]
  },
  {
   "title": "All time charged wh",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tesla_lifetime_energy_wh", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Current Session Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(tesla_vital_session_session_energy_wh / 1000) * $kw_cost",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}